# Generated by Django 4.2.4 on 2025-10-10 13:13

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Create UserProfile for all existing users."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    
    for user in User.objects.all():
        # Check if profile already exists
        if not UserProfile.objects.filter(user=user).exists():
            UserProfile.objects.create(user=user, expired=False)


def reverse_create_user_profiles(apps, schema_editor):
    """Remove all UserProfiles (for rollback)."""
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("auth", "__latest__"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_user_profiles),
    ]
