# Generated by Django 4.2.4 on 2025-11-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_create_profiles_for_existing_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_token_jti",
                    models.CharField(
                        db_index=True,
                        help_text="JWT Token ID (jti) from refresh token",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "access_token_jti",
                    models.CharField(
                        blank=True,
                        help_text="JWT Token ID (jti) from access token",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        default="unknown",
                        help_text="Type of client: telegram_bot, website, mobile, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable device name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the client", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from HTTP headers",
                        null=True,
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram user ID for bot authentication",
                        null=True,
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this session expires"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this session is currently active",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="users_users_user_id_3887fe_idx",
                    ),
                    models.Index(
                        fields=["refresh_token_jti"],
                        name="users_users_refresh_2e6816_idx",
                    ),
                    models.Index(
                        fields=["telegram_user_id"],
                        name="users_users_telegra_0d915a_idx",
                    ),
                ],
            },
        ),
    ]
