# Generated by Django 4.2.4 on 2025-12-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_cohort_subscriberrequest_cohort"),
        ("users", "0002_create_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="User's current active cohort",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_members",
                to="blog.cohort",
            ),
        ),
    ]
