# Generated by Django 4.2.4 on 2026-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userprofile_subscriber_request_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="renewal_approved",
            field=models.BooleanField(
                default=False, help_text="Admin has approved the renewal"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="renewal_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the renewal was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="renewal_plan",
            field=models.CharField(
                blank=True,
                choices=[("6month", "6-Month Plan"), ("annual", "Annual Plan")],
                help_text="Selected plan for renewal",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="renewal_requested",
            field=models.BooleanField(
                default=False, help_text="User has requested membership renewal"
            ),
        ),
    ]
