# Generated by Django 4.2.4 on 2026-09-07 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_userprofile_renewal_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="discount",
            field=models.IntegerField(
                default=0, help_text="Discount percentage for renewal (0-100)"
            ),
        ),
        migrations.CreateModel(
            name="DiscountRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_value",
                    models.IntegerField(help_text="Discount percentage (0-100)"),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Date when discount becomes effective"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("excel_sync", "Excel Sync"),
                            ("manual", "Manual Entry"),
                            ("referral", "Referral"),
                            ("loyalty", "Loyalty Program"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        help_text="Source of the discount",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this discount"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created/synced",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Record",
                "verbose_name_plural": "Discount Records",
                "ordering": ["-effective_from", "-created_at"],
            },
        ),
    ]
