# Generated by Django 4.2.4 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userprofile_discount_discountrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="renewal_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the renewal request was submitted",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discountrecord",
            name="discount_value",
            field=models.IntegerField(help_text="Discount amount (in currency units)"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="discount",
            field=models.IntegerField(
                default=0, help_text="Discount amount for renewal (in currency units)"
            ),
        ),
    ]
