# Generated by Django 4.2.4 on 2024-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
    ]
