# Generated by Django 4.2.4 on 2024-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('PC', 'Pie Chart'), ('BC', 'Bar Chart')], default='PC', max_length=2, null=True),
        ),
    ]
