# Generated by Django 4.2.4 on 2024-04-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_survey_is_result_released'),
        ('survey', '0005_usersurveyresponse'),
    ]

    operations = [
    ]
