# Generated by Django 4.2.4 on 2024-05-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_merge_20240427_1011"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="question",
        ),
        migrations.AddField(
            model_name="response",
            name="choice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="survey.choice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="response",
            name="user_survey_response",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.usersurveyresponse",
            ),
            preserve_default=False,
        ),
    ]
