# Generated by Django 4.2.4 on 2024-05-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0008_usersurveyresponse_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="survey.question",
            ),
            preserve_default=False,
        ),
    ]
