# Generated by Django 4.2.4 on 2024-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0009_response_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersurveyresponse",
            name="guest_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
