# Generated by Django 4.2.4 on 2024-07-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_remove_response_choice_alter_response_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
