# Generated by Django 4.2.4 on 2024-01-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
