# Generated by Django 4.2.4 on 2024-02-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGroup',
            fields=[
                ('group_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='poll_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.activegroup'),
        ),
    ]
