# Generated by Django 4.2.4 on 2024-02-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='poll_group',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
