# Generated by Django 4.2.4 on 2024-02-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_activegroup_question_poll_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/poll_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='poll_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.activegroup'),
        ),
    ]
