# Generated by Django 4.2.4 on 2024-02-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_activegroup_question_poll_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegroup',
            name='group_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.activegroup'),
        ),
    ]
