# Generated by Django 4.2.4 on 2024-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_activegroup_alter_question_image_question_poll_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegroup',
            name='group_name',
            field=models.CharField(default='DefaultGroupName', max_length=200),
        ),
        migrations.AlterField(
            model_name='activegroup',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
