# Generated by Django 4.2.4 on 2024-02-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_activegroup_group_name_alter_activegroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegroup',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
    ]
