name: Continuous Integration

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort
    
    - name: Code formatting check with black
      run: |
        black --check --diff .
    
    - name: Import sorting check with isort
      run: |
        isort --check-only --diff .
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Create .env file for testing
      run: |
        cd mmdt
        cat > .env << EOF
        SECRET_KEY=test-secret-key-for-github-actions-ci
        DEBUG=True
        EMAIL_HOST_PASSWORD=test-password
        EOF
    
    - name: Run Django system checks
      run: |
        cd mmdt
        python manage.py check --deploy
    
    - name: Run migrations check
      run: |
        cd mmdt
        python manage.py makemigrations --check --dry-run
    
    - name: Run tests
      run: |
        cd mmdt
        python manage.py test --verbosity=2
    
    - name: Test coverage
      run: |
        cd mmdt
        coverage run --source='.' manage.py test
        coverage report --fail-under=80
    
    - name: Security check
      run: |
        pip install safety
        safety check --json
