name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file for testing
      run: |
        cd mmdt
        cat > .env << EOF
        SECRET_KEY=test-secret-key-for-github-actions
        DEBUG=True
        EMAIL_HOST_PASSWORD=test-password
        EOF
    
    - name: Run migrations
      run: |
        cd mmdt
        python manage.py migrate
    
    - name: Run Django system checks
      run: |
        cd mmdt
        python manage.py check --deploy
    
    - name: Run tests with coverage
      run: |
        cd mmdt
        coverage run --source='.' manage.py test blog.tests --verbosity=2
    
    - name: Generate coverage report
      run: |
        cd mmdt
        coverage report --include="blog/*" --show-missing
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./mmdt/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Run all tests
      run: |
        cd mmdt
        python manage.py test --verbosity=2

    - name: Lint code
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Security check
      run: |
        safety check
        bandit -r mmdt/ -f json -o bandit-report.json || true
