# Generated by Django 4.2.4 on 2025-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribers_only',
            field=models.BooleanField(default=False),
        ),
    ]
