# Generated by Django 4.2.4 on 2025-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscriberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberrequest',
            name='plan',
            field=models.CharField(choices=[('6month', '6-Month Plan'), ('annual', 'Annual Plan')], default='6month', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriberrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
