# Generated by Django 4.2.4 on 2025-02-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscriberrequest_plan_subscriberrequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberrequest',
            name='looking_for_job',
        ),
    ]
