# Generated by Django 4.2.4 on 2025-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_subscriberrequest_looking_for_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberrequest',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscriberrequest',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_subscriber_email'),
        ),
    ]
