# Generated by Django 4.2.4 on 2025-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_subscriberrequest_mmdt_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberrequest",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
