# Generated by Django 4.2.4 on 2025-12-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_subscriberrequest_telegram_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "cohort_id",
                    models.CharField(
                        help_text="Format: YYYY_MM (e.g., 2025_01)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'January 2025 Cohort')",
                        max_length=200,
                    ),
                ),
                (
                    "reg_start_date",
                    models.DateTimeField(help_text="Registration window start date"),
                ),
                (
                    "reg_end_date",
                    models.DateTimeField(help_text="Registration window end date"),
                ),
                (
                    "exp_date_6",
                    models.DateTimeField(help_text="Expiry date for 6-month plan"),
                ),
                (
                    "exp_date_12",
                    models.DateTimeField(help_text="Expiry date for 12-month plan"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this cohort accepting registrations?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cohort",
                "verbose_name_plural": "Cohorts",
                "ordering": ["-reg_start_date"],
            },
        ),
        migrations.AddField(
            model_name="subscriberrequest",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-assigned based on submission date",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriber_requests",
                to="blog.cohort",
            ),
        ),
    ]
