# Generated by Django 4.2.4 on 2025-12-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_subscriberrequest_telegram_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "cohort_id",
                    models.CharField(
                        help_text="Format: YYYY_MM (e.g., 2025_01)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'January 2025 Cohort')",
                        max_length=200,
                    ),
                ),
                (
                    "reg_start_date",
                    models.DateTimeField(help_text="Registration window start date"),
                ),
                (
                    "reg_end_date",
                    models.DateTimeField(help_text="Registration window end date"),
                ),
                (
                    "exp_date_6",
                    models.DateTimeField(help_text="Expiry date for 6-month plan"),
                ),
                (
                    "exp_date_12",
                    models.DateTimeField(help_text="Expiry date for 12-month plan"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this cohort accepting registrations?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cohort",
                "verbose_name_plural": "Cohorts",
                "ordering": ["-reg_start_date"],
            },
        ),
        migrations.AddField(
            model_name="subscriberrequest",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-assigned based on submission date",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriber_requests",
                to="blog.cohort",
            ),
        ),
        migrations.CreateModel(
            name="CohortMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("6month", "6-Month Plan"), ("annual", "Annual Plan")],
                        max_length=10,
                    ),
                ),
                ("expiry_date", models.DateTimeField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this membership"
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="blog.cohort",
                    ),
                ),
                (
                    "subscriber_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohort_memberships",
                        to="blog.subscriberrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cohort Membership",
                "verbose_name_plural": "Cohort Memberships",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="blog_cohort_user_id_358269_idx",
                    ),
                    models.Index(
                        fields=["cohort", "is_active"],
                        name="blog_cohort_cohort__308cff_idx",
                    ),
                ],
            },
        ),
    ]
