# Generated by Django 4.2.4 on 2026-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_cohort_subscriberrequest_cohort"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriberrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Subscriber Request",
                "verbose_name_plural": "Subscriber Requests",
            },
        ),
        migrations.RemoveConstraint(
            model_name="subscriberrequest",
            name="unique_subscriber_email",
        ),
        migrations.AddField(
            model_name="subscriberrequest",
            name="renewal_requested",
            field=models.BooleanField(default=False),
        ),
    ]
