# Generated by Django 4.2.4 on 2025-12-17 14:20

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def assign_historical_cohorts(apps, schema_editor):
    """Assign existing SubscriberRequests and UserProfiles to historical cohorts."""
    Cohort = apps.get_model('blog', 'Cohort')
    SubscriberRequest = apps.get_model('blog', 'SubscriberRequest')
    UserProfile = apps.get_model('users', 'UserProfile')
    CohortMembership = apps.get_model('blog', 'CohortMembership')

    unassigned_requests = SubscriberRequest.objects.filter(cohort__isnull=True, expiry_date__isnull=False)

    if not unassigned_requests.exists():
        return

    unique_expiry_dates = set(unassigned_requests.values_list('expiry_date', flat=True))
    cohort_mapping = {}

    for idx, expiry_date in enumerate(sorted(unique_expiry_dates), start=1):
        reg_end = expiry_date - timedelta(days=180)
        reg_start = reg_end - timedelta(days=30)

        cohort_id = f"HISTORICAL_{idx}"
        cohort, created = Cohort.objects.get_or_create(
            cohort_id=cohort_id,
            defaults={
                'name': f'Historical Cohort {idx}',
                'reg_start_date': reg_start,
                'reg_end_date': reg_end,
                'exp_date_6': expiry_date,
                'exp_date_12': expiry_date + timedelta(days=185),
                'is_active': False,
            }
        )
        cohort_mapping[expiry_date] = cohort

    for request in unassigned_requests:
        if request.expiry_date in cohort_mapping:
            request.cohort = cohort_mapping[request.expiry_date]
            request.save(update_fields=['cohort'])

    for profile in UserProfile.objects.filter(expiry_date__isnull=False):
        if profile.expiry_date in cohort_mapping:
            profile.current_cohort = cohort_mapping[profile.expiry_date]
            profile.save(update_fields=['current_cohort'])

            try:
                subscriber_request = SubscriberRequest.objects.filter(
                    email__iexact=profile.user.email,
                    status='approved'
                ).first()

                if subscriber_request:
                    CohortMembership.objects.get_or_create(
                        user=profile.user,
                        cohort=cohort_mapping[profile.expiry_date],
                        defaults={
                            'plan': subscriber_request.plan,
                            'expiry_date': profile.expiry_date,
                            'subscriber_request': subscriber_request,
                            'is_active': not profile.expired
                        }
                    )
            except Exception:
                pass


def reverse_assign_cohorts(apps, schema_editor):
    """Reverse the migration by removing historical cohorts."""
    Cohort = apps.get_model('blog', 'Cohort')
    SubscriberRequest = apps.get_model('blog', 'SubscriberRequest')
    UserProfile = apps.get_model('users', 'UserProfile')
    CohortMembership = apps.get_model('blog', 'CohortMembership')

    Cohort.objects.filter(cohort_id__startswith='HISTORICAL_').delete()
    SubscriberRequest.objects.filter(cohort__cohort_id__startswith='HISTORICAL_').update(cohort=None)
    UserProfile.objects.filter(current_cohort__cohort_id__startswith='HISTORICAL_').update(current_cohort=None)
    CohortMembership.objects.filter(cohort__cohort_id__startswith='HISTORICAL_').delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_cohort_subscriberrequest_cohort_cohortmembership"),
        ("users", "0003_userprofile_current_cohort"),
    ]

    operations = [
        migrations.RunPython(assign_historical_cohorts, reverse_assign_cohorts),
    ]
