# Generated by Django 4.2.4 on 2025-12-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_assign_historical_cohorts"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscriberrequest",
            name="unique_subscriber_email",
        ),
        migrations.AlterField(
            model_name="subscriberrequest",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="subscriberrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("email",),
                name="unique_pending_subscriber_email",
            ),
        ),
    ]
