# Generated by Django 4.2.4 on 2026-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_add_renewal_requested_to_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberrequest",
            name="renewal_plan",
            field=models.CharField(
                blank=True,
                choices=[("6month", "6-Month Plan"), ("annual", "Annual Plan")],
                max_length=10,
                null=True,
            ),
        ),
    ]
