# Generated by Django 4.2.4 on 2026-03-14 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_add_renewal_plan_to_subscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriberrequest",
            name="renewal_plan",
        ),
        migrations.RemoveField(
            model_name="subscriberrequest",
            name="renewal_requested",
        ),
    ]
